### ISSUE TITLE
Example: Unexpected Token

### ISSUE THREAD

**Issue by harryd100** [robertklep/nefit-easy-client#1]
Hi,
First of all, great job and many thanks for this library. I tried the example, but get the error:

/usr/local/lib/node_modules/nefit-easy-client/example/current-status.js:12
client.connect().then( () => {
                        ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by robertklep** [comment]
Hi @harryd100,

For this library to work you need at least Node v4.0.0. The error you're getting is caused by an older version of Node.

I'll update the documentation to reflect this requirement :-)

**Comment by tazdevl** [comment]
Some more background on the node.js https://www.domoticz.com/forum/viewtopic.php?f=4&t=9653

**Comment by robertklep** [comment]
Thanks @tazdevl :+1:

**Comment by harryd100** [comment]
@robertklep, thanks works with Node.js 4.2.4. Only wondering about the System pressure
Temperature is set to 21.0°C, current is 21.5°C.
Outside temperature is 9.0°C.
System pressure is 25.5 bar.

**Comment by robertklep** [comment]
@harryd100 uh yeah that's looking a bit strange ;-)

If you install the most recent version as a Node module (explained [here](https://github.com/robertklep/nefit-easy-client#install-it-as-a-node-module)), using the `-g` flag, you get a CLI tool called `easy`, with which you can send semi-raw commands to the backend.

The one for the system pressure is this (I included the response for my system):

```
$ easy get /system/appliance/systemPressure
{
  "id": "/system/appliance/systemPressure",
  "type": "floatValue",
  "recordable": 0,
  "writeable": 0,
  "value": 1.3,
  "unitOfMeasure": "bar",
  "minValue": 0,
  "maxValue": 25
}
```

If you can get this working, can you create a new issue and post the raw response there?
