### ISSUE TITLE
High systemPressure

### ISSUE THREAD

**Issue by harryd100** [robertklep/nefit-easy-client#2]
After getting the client running, I noticed a (very) high systemPressure of 25.5 Bar

Running: easy get /system/appliance/systemPressure shows

{"id":"/system/appliance/systemPressure","type":"floatValue","recordable":0,"writeable":0,"value":25.5,"unitOfMeasure":"bar","minValue":0,"maxValue":25}

Could this be because I have an Ecomline HR (does not support cv-waterpressure through Easy Connect)?

**Comment by robertklep** [comment]
I believe that the Ecomline is an older model (I used to have one, replaced it with a Trendline almost two years ago)?

If it doesn't support water pressure in the iOS/Android app, this library (which uses the same data as the apps) won't be able to support it either. The values returned don't make sense (25.5 exceeds the maximum of 25) so I think it's fair to say that you shouldn't trust it 😀

**Comment by harryd100** [comment]
Ok, thanks. It also does not support water pressure in the Android App. so I think you are right.
BTW, great piece of reverse engineering.
