### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by dutchsea** [robertklep/nefit-easy-client#3]
Installed the npm package again on Raspberry Pi 2B now after upgrading to node 4.0.0

Below the errors

pi@raspberrypi ~ $ npm install robertklep/nefit-easy-client [-g]
npm ERR! addLocal Could not install /home/pi/[-g]
npm ERR! Linux 4.1.13-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "robertklep/nefit-easy-client" "[-g]"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! path /home/pi/[-g]
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/[-g]'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

**Comment by robertklep** [comment]
The brackets signify that the `-g` option is optional, so it means that you can run one of these:

```
$ npm install robertklep/nefit-easy-client
```

or:

```
$ npm install robertklep/nefit-easy-client -g
```

**Comment by dutchsea** [comment]
Hoi Robert,

Dank voor de uitleg. Ik ben een volledige beginner in Unix/Linux, vandaar....

Gr,

Wouter

Op 1 jan. 2016 om 21:34 heeft Robert Klep <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

The brackets signify that the -g option is optional, so it means that you can run one of these:

$ npm install robertklep/nefit-easy-client

or:

$ npm install robertklep/nefit-easy-client -g

##

**Comment by robertklep** [comment]
@dutchsea geen probleem, ik lijd aan beroepsdeformatie waardoor ik denk dat dat soort teksten duidelijk zijn voor iedereen 😉

**Comment by dutchsea** [comment]
Mooi werk Robert. Er wordt al door andere gebruik van gemaakt.
Zie forum:  http://www.domoticz.com/forum/viewtopic.php?f=4&t=9653&hilit=Nefit
Ben jij een gebruiker van Domoticz?

Gr Wouter

Op 2 jan. 2016 om 08:34 heeft Robert Klep <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

@dutchseahttps://github.com/dutchsea geen probleem, ik lijd aan beroepsdeformatie waardoor ik denk dat dat soort teksten duidelijk zijn voor iedereen ?

##

**Comment by robertklep** [comment]
@dutchsea nee, ik ben geen domoticz gebruiker, maar ik hou die thread wel een beetje bij. Mooi dat er gebruik gemaakt van wordt, daar is het ook voor bedoeld 😀

**Comment by pascalbianca** [comment]
Ik dit met het volgende probleem.
Ik heb alles zoals hierboven ook geinstalleerd en gedaan.
Heb mijn nefit gegeven als volgend ingevoerd.:
```
pi@raspberrypi:~/nefit-easy-client $ export NEFIT_SERIAL_NUMBER=123456789

pi@raspberrypi:~/nefit-easy-client $ export NEFIT_ACCESS_KEY=cdaUD7hjbwrAAZDD

pi@raspberrypi:~/nefit-easy-client $ export NEFIT_PASSWORD="testje01"
```

BTW de gegevens die ik heb geplaatst zijn aangepast, dus zijn bedoeld om te weten of de juiste indeling is gebruikt.

Nu krijg ik de melding als ik pi@raspberrypi:~/nefit-easy-client $ node example/current-status.js
invul het volgende.:
error XMPP authentication failure

Wat doe ik fout of wat is er fout help!!
Er kan mij niemand helpen hiermee.

**Comment by robertklep** [comment]
@pascalbianca `nefit-easy-client` wordt niet meer bijgehouden en is vervangen door verschillende andere modules die hier genoemd worden: https://github.com/robertklep/nefit-easy-client#deprecated

Het makkelijkst om mee te beginnen is [`nefit-easy-cli`](https://github.com/robertklep/nefit-easy-cli), die installeert een command line utility waarmee je de Easy kunt uitlezen.

**Comment by robertklep** [comment]
@pascalbianca overigens kan het zijn dat "vreemde" karakters in het wachtwoord, bijvoorbeeld uitroeptekens, problemen opleveren.

**Comment by pascalbianca** [comment]
Ik heb het nu zover dat het loopt krijg nu dat de server loopt, maar vul ik op mijn eigen laptop het ip adres met poortnummer krijg ik een pagina met de tekst: Cannot GET / en de titel van het tapblad is error

**Comment by robertklep** [comment]
@pascalbianca de server is alleen voor specifieke gevallen handig, bv als doorgeefluik voor andere domoticasystemen, niet voor normaal gebruik in een browser.

**Comment by pascalbianca** [comment]
klopt ik maak gebruik van domoticz.
Maar als ik die example/current-status.js van je gebruik krijg ik rare meldingen allemaal.
Dus als ik het goed gebruik zou hij het via de domoticz wel moeten werken nu dan?
Zag ook dat je ergens melde dat je die site kende en af en toe mee keek.

**Comment by pascalbianca** [comment]
ik heb het werkend, maar kunt u mij misschien helpen met het volgende.
Wil dus als de pi opstart dat hij mij die server mee opstart zonder dat ik die met de hand moet doen.
Hoe doe ik dit?

**Comment by robertklep** [comment]
@pascalbianca dat kun je waarschijnlijk beter even op een Domoticz-forum vragen, die hebben daar vast meer ervaring mee.

**Comment by pascalbianca** [comment]
ook met mijn vraag wat zich net kruiste?

> Wil dus als de pi opstart dat hij mij die server mee opstart zonder dat ik die met de hand moet doen.
> Hoe doe ik dit?

**Comment by robertklep** [comment]
Ja, juist om die vraag (automatisch opstarten) beantwoord te krijgen :)

**Comment by pascalbianca** [comment]
oke. toch super bedankt dat u de moeite hebt genomen om me te helpen.
ga zo door met dit ongelooflijk werk.
