### ISSUE TITLE
Error: INVALID_RESPONSE when using the CLI put command

### ISSUE THREAD

**Issue by ghost** [robertklep/nefit-easy-client#5]
The put command is not working.

root@linux:~/nefit-easy-client# ./bin/easy get /heatingCircuits/hc1/temperatureRoomManual
{"id":"/heatingCircuits/hc1/temperatureRoomManual","type":"floatValue","recordable":0,"writeable":1,"value":19,"unitOfMeasure":"C","minValue":5,"maxValue":30}
root@linux:~/nefit-easy-client# ./bin/easy status
{"user mode":"clock","clock program":"auto","in house status":"ok","in house temp":21.7,"boiler indicator":"off","control":"room","temp override duration":0,"current switchpoint":36,"ps active":true,"fp active":false,"temp override":true,"holiday mode":false,"boiler block":null,"boiler lock":null,"boiler maintainance":null,"temp setpoint":19,"temp override temp setpoint":19,"temp manual setpoint":19,"hed enabled":null,"hed device at home":null,"outdoor temp":5,"outdoor source type":"virtual"}
root@linux:~/nefit-easy-client# ./bin/easy put /heatingCircuits/hc1/temperatureRoomManual 20
{ [Error: INVALID_RESPONSE]
  response: 
   { protocolVersion: 'HTTP/1.0',
     statusCode: '400',
     statusMessage: 'Bad Request',
     headers: { 'Content-Type': 'application/json', connection: 'close' },
     body: '' } }
root@linux:~/nefit-easy-client# ./bin/easy status
{"user mode":"clock","clock program":"auto","in house status":"ok","in house temp":21.7,"boiler indicator":"off","control":"room","temp override duration":0,"current switchpoint":36,"ps active":true,"fp active":false,"temp override":true,"holiday mode":false,"boiler block":null,"boiler lock":null,"boiler maintainance":null,"temp setpoint":19,"temp override temp setpoint":19,"temp manual setpoint":19,"hed enabled":null,"hed device at home":null,"outdoor temp":5,"outdoor source type":"virtual"}
root@linux:~/nefit-easy-client#

**Comment by ghost** [comment]
Also does not work for other commands.

root@linux:~/nefit-easy-client# ./bin/easy put /heatingCircuits/hc1/manualTempOverride/status "on"
{ [Error: INVALID_RESPONSE]
  response: 
   { protocolVersion: 'HTTP/1.0',
     statusCode: '400',
     statusMessage: 'Bad Request',
     headers: { 'Content-Type': 'application/json', connection: 'close' },
     body: '' } }
root@linux:~/nefit-easy-client#

**Comment by robertklep** [comment]
The `put` command is rather low-level, so the backend expects the data to be formatted in a particular way.

In your first case, try this:

```
$ easy put /heatingCircuits/hc1/temperatureRoomManual '{"value":20}'
```

Second:

```
$ easy put /heatingCircuits/hc1/manualTempOverride/status '{"value":"on"}'
```

**Comment by ghost** [comment]
That works! Thanks.
