### ISSUE TITLE
Easy pressure reporting high value

### ISSUE THREAD

**Issue by dutchsea** [robertklep/nefit-easy-client#6]
My easy pressure results in quite a high amount, 25.5 bar, where i expect something between 1 and 2

{"pressure":25.5,"unit":"bar"}

Any ideas why this is the case?

**Comment by rostykk** [comment]
@dutchsea it means you CV physically can't provide pressure reading from UBA (in iOS/Android app its greyed out)
Reffer to "Weergave cv-waterdruk" in:
![Ondersteunde_toestellen](http://clip2net.com/clip/m44058/de01b-clip-253kb.png)

**Comment by dutchsea** [comment]
Clear, thanks
